### ISSUE TITLE
small repairs on the header

### ISSUE THREAD

**Issue by FalkoFuroro** [Lichtwerkstatt/XRTL_SPA#100]
Desktop
- create a mouseover info for the Icon next to Overlay with "beam path"
- rename mouseover info: Information -> Info
- rename mouseover info: Webcam -> Cam

Smartphone:
- rename: Tags -> Labels
- put a space between Icons and Texts in the drop-down menu

Desktop and Smartphone:
- rename "Connetion" to "connect"
- rename "connect" after connection to "disconnect" and vice versa
- [ ]     move "Labels" to he middle next to "beam path"
- [ ]     rename Mouseover "Beam path" to "Beam Path"
- [ ]     rename and reorder Dropdown Items "On" / "Off" / "Beamsplitter" to "On" / "On (with Beamsplitter)" / "Off"

**Comment by Claralein** [comment]
Desktop

- [x]     create a mouseover info for the Icon next to Overlay with "beam path"
- [x]     rename mouseover info: Information -> Info
- [x]     rename mouseover info: Webcam -> Cam

Smartphone:

- [x]     rename: Tags -> Labels
- [x]     put a space between Icons and Texts in the drop-down menu

Desktop and Smartphone:

- [x]    rename "Connetion" to "connect"
- [x]    rename "connect" after connection to "disconnect" and vice versa
- [ ]     move "Labels" to he middle next to "beam path"
- [x]     rename Mouseover "Beam path" to "Beam Path"
- [x]     rename and reorder Dropdown Items "On" / "Off" / "Beamsplitter" to "On" / "On (with Beamsplitter)" / "Off"
