### ISSUE TITLE
Top View of Experiment - Resolution

### ISSUE THREAD

**Issue by FalkoFuroro** [Lichtwerkstatt/XRTL_SPA#105]
Should automatically be set to **1024x768**, so that even after a restart, the picture is "nice" again.
We should probably set the contrast and exposure to a fixed value in the same way.

**Comment by Claralein** [comment]
I have now set the camera with the desired settings.
Feel free to check if you like it :)

If so, the issue can be closed.

**Comment by FalkoFuroro** [comment]
Can we have a command for the chat that sets the camera to the desired settings? Please!

**Comment by Claralein** [comment]
The highest resolution can now be set in the chat with !cam
