### ISSUE TITLE
Secondary Beamsplitter should move in virtual model

### ISSUE THREAD

**Issue by jkbeetle** [Lichtwerkstatt/XRTL_SPA#109]
The virtual model is intended to be a digital twin, and therefor should represent the real experiment as close as possible. So the rotational position of the secondary beamsplitter has to rotate up and down on user input, resp. the state.

Accordingly the beam-visualization should change as well depending on the status of the secondary beamsplitter and should **not** be selectable by user input.

Implementation:
- change base model to a configuration without secondary beamsplitter acrylic plate
- import plate as extra fbx object 
- rotate depending on status of beam splitter component
- bonus: animate movement 
- delete sub-options to display beam visualization
- show beam visualization mode depending on component

**Comment by LuponasAtWork** [comment]
point 1 and 2 of implementation are already done. Currently, I can not access the status of the components in the experiment model ("mesh file"). @Claralein any idea how to address that?

**Comment by Claralein** [comment]
The virtual model is intended to be a digital twin, and therefor should represent the real experiment as close as possible. So the rotational position of the secondary beamsplitter has to rotate up and down on user input, resp. the state.

Accordingly the beam-visualization should change as well depending on the status of the secondary beamsplitter and should not be selectable by user input.

Implementation:
- [x]  change base model to a configuration without secondary beamsplitter acrylic plate
- [x]    import plate as extra fbx object
- [x]   rotate depending on status of beam splitter component
- [ ]   bonus: animate movement
- [x]     delete sub-options to display beam visualization
- [x]     show beam visualization mode depending on component

**Comment by Claralein** [comment]
@LuponasAtWork 
You could write a new function in the AppContext that changes the value of the varaibale in the AppContext based on the status of the beamSplitter.

**Comment by Claralein** [comment]
@LuponasAtWork 

I have prepared everything for the beamsplitter animation. 
There is a variable (**beamSplitterState**), which is reset with change of the beam splitter (true... in the beam path, false... not in the beam path).

**Comment by LuponasAtWork** [comment]
I did my part (besides the bonus). There are now some unused vars and I'm not sure if they might be still needed, so I left them in the NavBar.js for now.

**Comment by Claralein** [comment]
@LuponasAtWork 
Can this issue be closed?

**Comment by LuponasAtWork** [comment]
I'm afraid so. I don't feel like digging into the huge field of animation with three.js right now.
