### ISSUE TITLE
Restart of components not working

### ISSUE THREAD

**Issue by Claralein** [Lichtwerkstatt/XRTL_SPA#110]
- [x] The restart command "*" does not work as it should

**Comment by doomke** [comment]
recognition of the wildcard was note yet enabled, but should work with the next [hardware update](https://github.com/Lichtwerkstatt/XRTL_Hardware/commit/37da351d4a8f34074cc9efc2950c8860f23f6015). Please be careful and use sparsely: every single module receiving this will react on it.
