### ISSUE TITLE
Screen Window breaks on re-opening

### ISSUE THREAD

**Issue by LuponasAtWork** [Lichtwerkstatt/XRTL_SPA#111]
When the screen window is closed while the settings are active, the layout is broken on reopening the window. Changing to the i tab restores the original layout.

**Comment by Claralein** [comment]
I already fixed that in the commit earlier.
Maybe you forgot to pull?

https://github.com/Lichtwerkstatt/XRTL_SPA/commit/d597ec7d762945b226330353e158ae033442b374
