### ISSUE TITLE
Identify component

### ISSUE THREAD

**Issue by Claralein** [Lichtwerkstatt/XRTL_SPA#115]
With clicking on the i symbol in a component window sends a command to the selected component, whereupon the LED ring of the component lights up briefly.

- [x] Transfer command 
- [x] Insert command into app 
- [x] ESP listens to command

**Comment by doomke** [comment]
For the implementation we should agree on a command for the identification process. Nothing is implemented on the hardware site yet, so I suggest something like the following:

```json
[
    "command",
    {
        "controlId":"stepper",    <- controlId of the module to identify
        "identify":3000           <- duration (in ms) to light up the LED
    }
]
```

~Alternatively we could use `"identify":true` with a standard value for the duration, whatever is more convenient/feels appropriate.~

**Comment by doomke** [comment]
`identify` command has been implemented for stepper motors, servo motors and outputs. I tested it locally only, please test within the server environment.

**Comment by Claralein** [comment]
Works correctly!
