### ISSUE TITLE
establish and integrate camera stream

### ISSUE THREAD

**Issue by jkbeetle** [Lichtwerkstatt/XRTL_SPA#12]
ESP32:
- https://github.com/Inglebard/esp32cam-relay
-  [SocketIO](https://stackoverflow.com/questions/66549640/esp32-cam-fastest-way-to-stream-video-output-to-nodejs-server-with-socketio) (maybe bad decision) 
- [ESP32 Cam Webserver](https://github.com/espressif/arduino-esp32/blob/master/libraries/ESP32/examples/Camera/CameraWebServer/CameraWebServer.ino)

- [x] prepare ESP32-cam module
- [x] build socket connection
- [x] maybe test raspi & webcam as component // Himbeere with webcam or HQ cam

**Comment by Claralein** [comment]
https://www.youtube.com/watch?v=qexy4Ph66JE

Damit ich es wiederfinde

**Comment by Claralein** [comment]
Facinge Mode 

![grafik](https://user-images.githubusercontent.com/93766288/146364461-7fcdf67a-8830-43ec-a56f-a924663874e1.png)

**Comment by Claralein** [comment]
https://www.npmjs.com/package/raspberrypi-node-camera-web-streamer

**Comment by doomke** [comment]
The limiting factor for streaming from an ESP32 seems to be the conversion to base64 -- can we instead just transmit the frames as binary and leave any conversion to the (hopefully) more potent client side, as for example [here](http://www.iotsharing.com/2020/03/demo-48-using-websocket-for-camera-live.html)?

**Comment by Claralein** [comment]
index.html 


<!DOCTYPE html>
<html lang="de">

<head>
</head>

<body>
    <canvas id='yourCanvasId' width="1000" height="1000"></canvas>
    <script src="/socket.io/socket.io.js"></script>
    <script type="text/javascript">
        var socket = io.connect('http://localhost:7000');
        socket.on('pic', function (data) {
            var uint8Arr = new Uint8Array(data.buffer);
            var binary = '';
            for (var i = 0; i < uint8Arr.length; i++) {
                binary += String.fromCharCode(uint8Arr[i]);
            }
            var base64String = window.btoa(binary);

            var img = new Image();
            img.onload = function () {
                var canvas = document.getElementById('yourCanvasId');
                var ctx = canvas.getContext('2d');
                var x = 0, y = 0;
                ctx.drawImage(this, x, y);
            }
            img.src = 'data:image/jpg;base64,' + base64String;
        });
    </script>


</body>

</html>

**Comment by Claralein** [comment]
index.js

const express = require('express');
const app = express();
const http = require('http');
const server = http.createServer(app);

const io = require('socket.io')(server, {
  cors: {
    origin: '*'
  }
})
const fs = require('fs');
const path = require('path');

app.get('/', (req, res) => {
  res.sendFile(__dirname + '/index.html');
});


io.on('connection', function(socket){
  console.log("Connected");
  socket.on('pic', (data)=>{

      socket.broadcast.emit('pic', { buffer: data.image });
  
  });
});

server.listen(7000, () => {
  console.log('listening on *:7000');
});

**Comment by Claralein** [comment]
stream.js


  useEffect(() => {
    socketCtx.socket.on('pic', function (data){
      var uint8Arr = new Uint8Array(data.buffer); 
      var binary = ''; 
      for (var i = 0; i < uint8Arr.length; i++) { 
        binary += String.fromCharCode(uint8Arr[i]); 
        } 
      var base64String = window.btoa(binary);

      var img = new Image();
      img.onload = function () {
        var canvas = document.getElementById('ScreenCanvas');
        var ctx = canvas.getContext('2d');
        var x = 0, y = 0;
        ctx.drawImage(this, x, y);
      }
      img.src = 'data:image/jpg;base64,' + base64String;
    });
  }, [])

  return (
    <Window
      header={props.title + " (" + props.id + ")"}
      top={props.top}
      left={props.left}
      width="800px"
      height="600px"
      onClose={handleCloseWindow}
    >
      <canvas id='ScreenCanvas' width="800" height="600"></canvas>

    </Window>
  );
};

export default Stream;

**Comment by jkbeetle** [comment]
@Claralein 
doesnt seem to work, server breaks and stops execution
Error ReferenceError: componentID not defined at Socket.<anonymous>
/home/pi/XRTL_SPA/server/server.himbeere.js:125:19

**Comment by jkbeetle** [comment]
tried again, now nothing happens (no breakdown, but also no images and no logged commands send and retrieved)

**Comment by Claralein** [comment]
Hopefully fixed @jkbeetle!

**Comment by jkbeetle** [comment]
Let's hope all together!
