### ISSUE TITLE
Top Light

### ISSUE THREAD

**Issue by FalkoFuroro** [Lichtwerkstatt/XRTL_SPA#128]
We need a switchable top light.

- [x] create a real one @FalkoFuroro 
- [x] make an entri on ESP32 @FalkoFuroro 
- [x] create a control button @Claralein

**Comment by Claralein** [comment]
create a control button in ...

- [x] Michelson Advanced
- [x] ShowCase
- [x] Adpative Optics
- [x] Fundamentals

**Comment by FalkoFuroro** [comment]
- [x]  setup an ESP32-Board (_MI\_V_) for **MI** -> control_id = "_relay\_light_"
- [x]  setup an ESP32-Board (_SC\_V_) for **Showcase** -> control_id = "_relay\_light_"
