### ISSUE TITLE
automatic startup of Himbeere

### ISSUE THREAD

**Issue by jkbeetle** [Lichtwerkstatt/XRTL_SPA#13]
- [x] implement bash script for startup of himbeere with node server.js
- [x] include automatic update from git repo if possible

optional:
- [x] status LED for operation without screen

**Comment by jkbeetle** [comment]
library for talking to gpio pins from nodejs
https://www.npmjs.com/package/rpi-gpio

**Comment by Claralein** [comment]
Autostart von dem Bash Script:
![grafik](https://user-images.githubusercontent.com/93766288/145589558-c38ca9e6-8255-4317-b95a-3ac07990440a.png)


Restart ssh service:
sudo service ssh restart

**Comment by Claralein** [comment]
Skript für Auschalten per Button 

![grafik](https://user-images.githubusercontent.com/93766288/145987825-1dbc21d1-b4b0-4081-a681-ff85942d39db.png)


Und dann unter "/etc/rc.local" eine Zeile eingefügt mit "python <Pfad des Skriptes>"

**Comment by jkbeetle** [comment]
done :)
