### ISSUE TITLE
Disabling the Overview Cam Button when the Cam-in-BG view is selected.

### ISSUE THREAD

**Issue by FalkoFuroro** [Lichtwerkstatt/XRTL_SPA#130]
... otherwise, executing it will lead to undesirable effects.

![image](https://github.com/Lichtwerkstatt/XRTL_SPA/assets/94687478/536d6d74-2e57-4704-81a4-4d94be587e47)

**Comment by Claralein** [comment]
- [x] Michelson Advanced
- [x] ShowCase
- [x] Adpative Optics

**Comment by Claralein** [comment]
I have added this to all current experiment branches.
