### ISSUE TITLE
MichelsonAdvanced - changes that still need to be made

### ISSUE THREAD

**Issue by Claralein** [Lichtwerkstatt/XRTL_SPA#132]
Please insert the descriptions for the following components:
- [x] Multi Component Selection
- [x] Glass Plate Rotation Stage
- [x] Mirror Changing Stage
- [x] Heatable Mirror Stage

Adaptation of the DescriptiveTag for the 
- [x] Red LED
- [x] White LED 
- [x] Beamsplitter

Should the 
- [x] BeamSplitter 
- [x] Lens
- [x] Cube
have a window?

If yes, please insert the following
- [x] DescriptiveTag
- [x] #137
- [x] Add as DescriptionOnly component in the experiment file 
- [x] Add a new description in "client/src/components/experiment/ComponentDescription" 
- [x] Link this file in DescriptionHandler (client/src/components/experiment/ComponentDescription/DescriptionHandler.js)

**Comment by LuponasAtWork** [comment]
Descriptions of the multiple selectable components combined in the ExperimentSelection component.

**Comment by LuponasAtWork** [comment]
I assume the last open task should refer to the 3D model, in that case it's done.
