### ISSUE TITLE
Window rendering list problem

### ISSUE THREAD

**Issue by FalkoFuroro** [Lichtwerkstatt/XRTL_SPA#135]
The function **toggleSelectedComp** is not working well within the 2D-view.
The list **selectedComps** seems to be not updated in every step.

_Warning: Very confusing description of a problem that is not understood, may contain nuts._

**Comment by CanonDieCamera** [comment]
Bracket for adding components to selectedComps were at wrong position. setSelectedComps(prev => new Set(prev.add(compId))); to setSelectedComps(prev => new Set(prev).add(compId)); Same for roomComponents
