### ISSUE TITLE
Failproof ESP Controller

### ISSUE THREAD

**Issue by jkbeetle** [Lichtwerkstatt/XRTL_SPA#22]
can we make the ESPs more fail proof? 
- [x] auto wifi reconnect 
- [x] save wifi credentials (and other future environment parameters) in extra file which gets imported but not published on github (using .gitignore)
- [x] auto socket reconnect

optional:
- [ ] offer a template / boilerplate script for future dev of mounts with WiFi and Socket functionality

**Comment by doomke** [comment]
possible solutions:

1. autoreconnect should already be activated by default but we can set the corresponding flags to make sure
2. using LittleFS we can store an additional config file in the ESP's flash storage (implementation coming soon)
3. autoreconnect might already be implemented, a test environment to emulate disconnects would be highly appreciated

**Comment by doomke** [comment]
Issues 1-3 have been taken care of:

- ESPs can be configured via a settings file 
- WiFi automatic reconnect enabled
- socketIO automatic reconnect works as intended (verified)
