### ISSUE TITLE
Server GUI

### ISSUE THREAD

**Issue by jkbeetle** [Lichtwerkstatt/XRTL_SPA#43]
we need a nice Server GUI to be shown on Raspberry (Touch Screen). 

- [x] find and decide on GUI library (python)
- [x] show logs as been done on console
- [x] show component status (on/offline, busy, parameters, last update)
- [x] show logged on users
- [x] possibility of manual commands to test and configure experiment
- buttons: 
  - [x] ACTIVATE (allows access of components)
  - [x] SHUTDOWN
  - [x] RESET (reset all components to initial pose)
  - [x] INIT (set initial pose)
- [x] nice graphics, icons and animation! 😎

**Comment by Claralein** [comment]
We will use the Kivy GUI library (Python) as it runs on a Raspberry Pi and it supports multi-touch.
