### ISSUE TITLE
Enable SocketIO Connection on an ESP32

### ISSUE THREAD

**Issue by jkbeetle** [Lichtwerkstatt/XRTL_SPA#6]
trying [this](https://www.youtube.com/watch?v=CtMBn5Td3us&t=2674s&ab_channel=SupaponPucknavin)

**Comment by doomke** [comment]
> trying [this](https://www.youtube.com/watch?v=CtMBn5Td3us&t=2674s&ab_channel=SupaponPucknavin)

The library used in the video is deprecated, I suggest switching to [WebSockets](https://github.com/Links2004/arduinoWebSockets) with an SocketIO subclass.

**Comment by jkbeetle** [comment]
well done @doomke  :)
