### ISSUE TITLE
browser based access

### ISSUE THREAD

**Issue by FalkoFuroro** [Lichtwerkstatt/XRTL_SPA#62]
Will it be possible in the future to simply visit a website, log in and then control the experiment?
At least as a university network participant.

Anders ausgedrückt: Der Versuch für die Vitrine ist fast fertig. Was muss jemand tun um diesen zu steuern und wird es da noch Änderungen geben?

**Comment by jkbeetle** [comment]
right now, there is no login needed. The idea is, that everyone can access the experiment via a URL (resp. a QR code). 
For later purposes like a practical training, where a defined group should be able to change the parameters in a controlled manner, a login and user management is reasonable and should be implemented
