### ISSUE TITLE
Enable commands to be entered in chat

### ISSUE THREAD

**Issue by FalkoFuroro** [Lichtwerkstatt/XRTL_SPA#88]
I would like to be able to send commands to the server via the chat.

For the beginning only three:

- [x] **#showcase** -> makes the simulation rotate and move certain motors in a continuous loop

- [x] **#showusers** -> lists all currently logged in users

- [x] **#reset** -> moves all actuators back to the starting position

**Comment by FalkoFuroro** [comment]
!reset
- [x] 2x KM 100
- [x] 1x Beamsplitter
- [x] 1x Linear Motion Stage

not: Screen and Power Supply

**Comment by FalkoFuroro** [comment]
**!user** 

- [x] does not work on localhost
- [x] please rename **!user** to **!users** or both

**Comment by Claralein** [comment]
@FalkoFuroro 
Can this issue be closed?
