### ISSUE TITLE
Renaming the components

### ISSUE THREAD

**Issue by FalkoFuroro** [Lichtwerkstatt/XRTL_SPA#89]
The components should have a **short generic name** and a more _technical description_.

Please rename the components as follows:

**Screen** 
_Polystyrene Viewing Screen_

**Linear Movable Mirror**
_SM1ZP/M Translation Mount_

**Reference Mirror**
_KM100 Double Rotary Control_

**Beam Splitter**
_50:50 Cube Beam Splitter_

**Retractable Beam Splitter**
_Simple Plate Beam Splitter_

**Lens**
_Bi-Convex 50mm Focal Length_

**Laser Alignment**
_KM100 Double Rotary Control_

**Power Supply**
_5V Laser Power Supply_

**Comment by Claralein** [comment]
Edits were implemented
