### ISSUE TITLE
Contents of the info windows of the components

### ISSUE THREAD

**Issue by FalkoFuroro** [Lichtwerkstatt/XRTL_SPA#90]
Please fill the info windows with the following texts:

**Screen** 
_Polystyrene Viewing Screen_
The screen in a Michelson interferometer setup displays an interference pattern consisting of bright and dark fringes. The location and spacing of these fringes provide information about the relative phase difference between the two light paths, which can be used to measure small changes in the optical path length of the sample beam.

**Linear Movable Mirror**
_SM1ZP/M Translation Mount_
The two beams of light are reflected by mirrors placed at a 90-degree angle to each other. This mirror is used to reflect the sample beam. The translation mount is designed to securely hold a mirror in place while offering repeatable linear travel using the precision micrometer actuator, which is graduated in 1 µm increments. This component is used to create a quantifiable change in the path length of the sample beam.

**Reference Mirror**
_KM100 Double Rotary Control_
The two beams of light are reflected by mirrors placed at a 90-degree angle to each other. This mirror is used to reflect the reference beam. The kinematic mirror mount is designed to securely hold a mirror in place while allowing fine tip and tilt adjustments.

**Beam Splitter**
_50:50 Cube Beam Splitter_
The beam splitter is a partially reflective surface that splits the incoming beam of light into two separate beams, known as the reference beam and the sample beam. This cube beam splitter is made up of two prisms that are cemented together.

**Retractable Beam Splitter**
_Simple Plate Beam Splitter_
This really simple plate beam splitter is made of an acrylic glass sheet and can be used to observe the interference pattern created on the second output of the Michelson interferometer.

**Lens**
_Bi-Convex 50mm Focal Length_
The lens is used to diverge the beam of laser light in order to illuminate a larger area of the screen and thereby to obtain an interference pattern consisting of light and dark rings (constructive or destructive interference, respectively). Without a lens, the laser would create only one spot on the screen, which is either very bright (constructive interference) or completely gone (destructive interference).

**Laser Alignment**
_KM100 Double Rotary Control_
A coherent light source such as a laser is used to illuminate the interferometer. When light waves are coherent, their peaks and troughs line up perfectly, resulting in a pattern of constructive and destructive interference that can produce beautiful and complex interference patterns. In contrast, light that is not coherent has randomly varying phases and does not produce well-defined interference patterns.

**Power Supply**
_5V Laser Power Supply_
The laser power supply provides the electrical energy necessary to excite the laser medium and generate the coherent beam of light. The laser module here is a class 2 laser, which does not require any protective eyewear. However, to avoid injury, do not look directly into the laser beam. ;)

**Comment by Claralein** [comment]
Done :)
Every component has a window now & it can be closed as well
