### ISSUE TITLE
Next Button for the Welcome window

### ISSUE THREAD

**Issue by FalkoFuroro** [Lichtwerkstatt/XRTL_SPA#93]
Please fill the Welcome Window with the three texts, whereby a next button should switch from the view of one text to the next:

- [x] Next Button
- [x] Back Button
- [x] Texts

Welcome to XRTL website, where you can remotely control a simple Michelson interferometer and observe the interference pattern. Whether you're a student, researcher, or enthusiast, our user-friendly platform enables you to explore the fascinating world of optics and interferometry at your own pace. With real-time access to our experimental setup, you can adjust the paths and observe the resulting interference pattern, learning about interference effects and the wave-like nature of light. Login and discover the possibilities of remote interferometry!

**Next:**

The main function of a Michelson interferometer is to measure small differences in the length of two light paths, which can provide information about the properties of a sample placed in one of the paths. To achieve this a single beam of light is split into two paths (sample beam and reference beam) and later recombined on a screen. Analyzing the resulting interference pattern can reveal even small changes.

**Next:**

Our remote experiment allows you to control the components of a Michelson interferometer by simply clicking on their virtual twin. This opens a window that allows you to adjust the settings. You can observe the resulting interference pattern by selecting the screen. Additionally, you can view the entire setup by clicking on the camera icon in the header. Whether you're an expert or a beginner, you can experiment and explore the physics of interferometry in any way you choose, either by playing around with the components or by following our detailed manual for a more structured approach. We encourage you to discover the fascinating world of optics and interferometry.

**Comment by jkbeetle** [comment]
I would prefer a more scrolling approach with a scrollbar on the side.
Clicking prev/next is only appropriate when you want to communicate a workflow.
Having to click for a coherent block of information may be perceived as frustrating by users.

**Comment by FalkoFuroro** [comment]
I would like to clarify the existing information of the texts with animations / GIFs and thought that one text and one animation per window would be less overloaded.

**Comment by FalkoFuroro** [comment]
The actual idea behind this window was:
To give someone who logs in to the showcase via smart device a super short guide on how things are operated.
On a smartphone, for example, scrollbars are very inefficient.

**Comment by Claralein** [comment]
@FalkoFuroro if you happy with the result, than please close the issue :)
